FROM python:alpine AS base
RUN apk add --no-cache python-dev \
	&& pip install --pip

WORKDIR /Decagon
ADD ./Decagon

RUN pip --no-cache-dir install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python"]
CMD ["app.py"]